# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9a968749b2d807c6169c5a62eb690ebbdab50634b4cafc58915d2d24b22fe99e4ff5c66c07238d835eea0aa7b5bea5d8fa27dd515546e642538354b5a74cf140

test:
  secret_key_base: 83257ed3e9a36d7d91135e7a182b535fd1913572b3d5f21f50967a7a2949e01b901c826b395581a20a0eeeaa9fdcb105cafa7df1d56c96b22561d4f940b829fd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
